export const LOAD_CONCEPTS_SUCCESS = "LOAD_CONCEPTS_SUCCESS"
export const LOAD_CONCEPTS_ERROR = "LOAD_CONCEPTS_ERROR"

export const NEW_CONCEPTS_SUCCESS = "NEW_CONCEPTS_SUCCESS"
export const NEW_CONCEPTS_ERROR = "NEW_CONCEPTS_ERROR"