export const START_LOADING_SCREEN = "START_LOADING_SCREEN"
export const END_LOADING_SCREEN = "END_LOADING_SCREEN"
export const END_LOADING_SCREEN_WITH_MESSAGE = "END_LOADING_SCREEN_WITH_MESSAGE"
export const RESET_LOADING_SCREEN = "RESET_LOADING_SCREEN"